import * as XLSX from "xlsx";
import { jsPDF } from "jspdf";
import "jspdf-autotable";

export type InventoryReportLayout = "stock_wise" | "batch_wise" | "expiry_wise" | "generic";

export type ReportMeta = {
  companyName: string;
  companyAddress?: string;
  reportTitle: string;
  layout: InventoryReportLayout;
  dateFrom: string;
  dateTo: string;
  reportDate: string;
  warehouse: string;
  category?: string;
  generatedBy: string;
};

export type StockWiseRow = {
  sno: number;
  itemCode: string;
  itemName: string;
  uom: string;
  openingQty: number;
  purchaseQty: number;
  salesQty: number;
  adjustQty: number;
  closingQty: number;
  unitCost: number;
  stockValue: number;
  gst: number;
  totalValue: number;
};

export type BatchWiseRow = {
  sno: number;
  batchNo: string;
  itemCode: string;
  itemName: string;
  warehouse: string;
  mfgDate: string;
  expiryDate: string;
  receivedQty: number;
  soldQty: number;
  balanceQty: number;
  unitCost: number;
  totalValue: number;
};

export type ExpiryWiseRow = {
  sno: number;
  itemCode: string;
  itemName: string;
  batchNo: string;
  mfgDate: string;
  expiryDate: string;
  daysRemaining: number;
  availableQty: number;
  warehouse: string;
  status: "Safe" | "Near Expiry" | "Expired";
};

function money(n: number) {
  return Number(n || 0).toLocaleString("en-SG", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

function qty(n: number) {
  return Number(n || 0).toLocaleString("en-SG", { minimumFractionDigits: 0, maximumFractionDigits: 3 });
}

function fmtDate(iso: string) {
  if (!iso) return "-";
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) {
    // already dd/mm/yyyy or plain string
    if (/^\d{4}-\d{2}-\d{2}/.test(iso)) {
      const [y, m, day] = iso.slice(0, 10).split("-");
      return `${day}/${m}/${y}`;
    }
    return iso;
  }
  const day = String(d.getDate()).padStart(2, "0");
  const m = String(d.getMonth() + 1).padStart(2, "0");
  return `${day}/${m}/${d.getFullYear()}`;
}

function layoutColor(layout: InventoryReportLayout): [number, number, number] {
  void layout;
  return [59, 130, 246]; // light blue (#3B82F6)
}

function safeFile(name: string) {
  return name.replace(/[^\w\-]+/g, "-").replace(/-+/g, "-").toLowerCase();
}

function drawHeader(doc: jsPDF, meta: ReportMeta, pageWidth: number) {
  const color = layoutColor(meta.layout);
  doc.setFillColor(...color);
  doc.rect(0, 0, pageWidth, 18, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("INVENTORY REPORTS", 14, 8);
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text("Print / PDF / Excel Friendly Reports", 14, 14);

  doc.setTextColor(17, 24, 39);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text(meta.companyName || "Company", 14, 28);

  if (meta.companyAddress) {
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(75, 85, 99);
    doc.text(meta.companyAddress, 14, 33);
  }

  // Title bar
  const titleY = meta.companyAddress ? 38 : 34;
  doc.setFillColor(...color);
  doc.roundedRect(14, titleY, pageWidth - 28, 10, 1, 1, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text(meta.reportTitle.toUpperCase(), 18, titleY + 6.5);

  // Meta grid
  const metaY = titleY + 16;
  doc.setTextColor(55, 65, 81);
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  const left = [
    `Date Range : ${fmtDate(meta.dateFrom)} - ${fmtDate(meta.dateTo)}`,
    `Report Date : ${fmtDate(meta.reportDate)}`,
    `Warehouse : ${meta.warehouse || "All Warehouses"}`,
  ];
  const right = [
    `Generated By : ${meta.generatedBy}`,
    meta.category ? `Category : ${meta.category}` : "",
  ].filter(Boolean);

  left.forEach((line, i) => doc.text(line, 14, metaY + i * 5));
  right.forEach((line, i) => doc.text(line, pageWidth / 2 + 10, metaY + i * 5));

  return metaY + Math.max(left.length, right.length) * 5 + 4;
}

function drawFooter(doc: jsPDF, pageWidth: number, pageHeight: number, page: number, total: number) {
  doc.setFontSize(7);
  doc.setTextColor(107, 114, 128);
  doc.setFont("helvetica", "normal");
  doc.text(`Page ${page} of ${total}`, pageWidth - 14, pageHeight - 8, { align: "right" });
}

export function exportStockWisePdf(meta: ReportMeta, rows: StockWiseRow[]) {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let startY = drawHeader(doc, { ...meta, layout: "stock_wise" }, pageWidth);

  const body = rows.map((r) => [
    r.sno,
    r.itemCode,
    r.itemName,
    r.uom,
    qty(r.openingQty),
    qty(r.purchaseQty),
    qty(r.salesQty),
    qty(r.adjustQty),
    qty(r.closingQty),
    money(r.unitCost),
    money(r.stockValue),
    money(r.gst),
    money(r.totalValue),
  ]);

  const totals = rows.reduce(
    (a, r) => ({
      opening: a.opening + r.openingQty,
      purchase: a.purchase + r.purchaseQty,
      sales: a.sales + r.salesQty,
      adjust: a.adjust + r.adjustQty,
      closing: a.closing + r.closingQty,
      value: a.value + r.stockValue,
      gst: a.gst + r.gst,
      total: a.total + r.totalValue,
    }),
    { opening: 0, purchase: 0, sales: 0, adjust: 0, closing: 0, value: 0, gst: 0, total: 0 },
  );

  (doc as any).autoTable({
    startY,
    head: [[
      "S.No.", "Item Code", "Item Name", "UOM",
      "Opening Qty", "Purchase Qty", "Sales Qty", "Adjust Qty", "Closing Qty",
      "Unit Cost (SGD)", "Stock Value (SGD)", "GST 9%", "Total Value (SGD)",
    ]],
    body,
    foot: [[
      "", "", "GRAND TOTAL", "",
      qty(totals.opening), qty(totals.purchase), qty(totals.sales), qty(totals.adjust), qty(totals.closing),
      "", money(totals.value), money(totals.gst), money(totals.total),
    ]],
    theme: "striped",
    styles: { fontSize: 7, cellPadding: 1.8, lineColor: [229, 231, 235], lineWidth: 0.1 },
    headStyles: { fillColor: layoutColor("stock_wise"), textColor: 255, fontStyle: "bold", fontSize: 7 },
    footStyles: { fillColor: [243, 244, 246], textColor: [17, 24, 39], fontStyle: "bold", fontSize: 7 },
    alternateRowStyles: { fillColor: [249, 250, 251] },
    margin: { left: 14, right: 14, bottom: 16 },
    didDrawPage: (data: any) => {
      if (data.pageNumber > 1) drawHeader(doc, { ...meta, layout: "stock_wise" }, pageWidth);
    },
  });

  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    drawFooter(doc, pageWidth, pageHeight, i, pageCount);
  }

  doc.save(`${safeFile(meta.reportTitle)}-${meta.reportDate}.pdf`);
}

export function exportBatchWisePdf(meta: ReportMeta, rows: BatchWiseRow[]) {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let startY = drawHeader(doc, { ...meta, layout: "batch_wise" }, pageWidth);

  const body = rows.map((r) => [
    r.sno, r.batchNo, r.itemCode, r.itemName, r.warehouse,
    fmtDate(r.mfgDate), fmtDate(r.expiryDate),
    qty(r.receivedQty), qty(r.soldQty), qty(r.balanceQty),
    money(r.unitCost), money(r.totalValue),
  ]);

  (doc as any).autoTable({
    startY,
    head: [[
      "S.No.", "Batch No.", "Item Code", "Item Name", "Warehouse",
      "Mfg. Date", "Expiry Date", "Received Qty", "Sold Qty", "Balance Qty",
      "Unit Cost (SGD)", "Total Value (SGD)",
    ]],
    body,
    theme: "striped",
    styles: { fontSize: 7, cellPadding: 1.8 },
    headStyles: { fillColor: layoutColor("batch_wise"), textColor: 255, fontStyle: "bold", fontSize: 7 },
    alternateRowStyles: { fillColor: [249, 250, 251] },
    margin: { left: 14, right: 14, bottom: 16 },
  });

  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    drawFooter(doc, pageWidth, pageHeight, i, pageCount);
  }
  doc.save(`${safeFile(meta.reportTitle)}-${meta.reportDate}.pdf`);
}

export function exportExpiryWisePdf(meta: ReportMeta, rows: ExpiryWiseRow[]) {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let startY = drawHeader(doc, { ...meta, layout: "expiry_wise" }, pageWidth);

  const body = rows.map((r) => [
    r.sno, r.itemCode, r.itemName, r.batchNo,
    fmtDate(r.mfgDate), fmtDate(r.expiryDate),
    r.daysRemaining, qty(r.availableQty), r.warehouse, r.status,
  ]);

  (doc as any).autoTable({
    startY,
    head: [[
      "S.No.", "Item Code", "Item Name", "Batch No.", "Mfg. Date", "Expiry Date",
      "Days Remaining", "Available Qty", "Warehouse", "Status",
    ]],
    body,
    theme: "striped",
    styles: { fontSize: 7, cellPadding: 1.8 },
    headStyles: { fillColor: layoutColor("expiry_wise"), textColor: 255, fontStyle: "bold", fontSize: 7 },
    alternateRowStyles: { fillColor: [249, 250, 251] },
    margin: { left: 14, right: 14, bottom: 16 },
    didParseCell: (data: any) => {
      if (data.section === "body" && data.column.index === 9) {
        const v = String(data.cell.raw);
        if (v === "Safe") {
          data.cell.styles.textColor = [22, 163, 74];
          data.cell.styles.fontStyle = "bold";
        } else if (v === "Near Expiry") {
          data.cell.styles.textColor = [234, 88, 12];
          data.cell.styles.fontStyle = "bold";
        } else if (v === "Expired") {
          data.cell.styles.textColor = [220, 38, 38];
          data.cell.styles.fontStyle = "bold";
        }
      }
    },
  });

  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    drawFooter(doc, pageWidth, pageHeight, i, pageCount);
  }
  doc.save(`${safeFile(meta.reportTitle)}-${meta.reportDate}.pdf`);
}

export function exportGenericPdf(meta: ReportMeta, rows: Record<string, string | number>[]) {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let startY = drawHeader(doc, { ...meta, layout: "generic" }, pageWidth);
  const keys = Object.keys(rows[0] || {});
  (doc as any).autoTable({
    startY,
    head: [keys],
    body: rows.map((r) => keys.map((k) => String(r[k] ?? ""))),
    theme: "striped",
    styles: { fontSize: 7, cellPadding: 1.8 },
    headStyles: { fillColor: layoutColor("generic"), textColor: 255, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [249, 250, 251] },
    margin: { left: 14, right: 14, bottom: 16 },
  });
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    drawFooter(doc, pageWidth, pageHeight, i, pageCount);
  }
  doc.save(`${safeFile(meta.reportTitle)}-${meta.reportDate}.pdf`);
}

function autoFitCols(aoa: (string | number)[][]): XLSX.ColInfo[] {
  const colCount = aoa.reduce((max, row) => Math.max(max, row.length), 0);
  const widths: number[] = Array.from({ length: colCount }, () => 10);

  for (const row of aoa) {
    for (let i = 0; i < row.length; i++) {
      const cell = row[i];
      const len = cell == null || cell === "" ? 0 : String(cell).length;
      if (len + 2 > widths[i]) widths[i] = len + 2;
    }
  }

  return widths.map((wch) => ({ wch: Math.min(Math.max(wch, 10), 48) }));
}

function sheetFromAoa(aoa: (string | number)[][]) {
  const ws = XLSX.utils.aoa_to_sheet(aoa);
  ws["!cols"] = autoFitCols(aoa);
  return ws;
}

function excelMetaRows(meta: ReportMeta): (string | number)[][] {
  const rows: (string | number)[][] = [
    ["INVENTORY REPORTS"],
    ["Print / PDF / Excel Friendly Reports"],
    [],
    [meta.companyName],
  ];
  if (meta.companyAddress) rows.push([meta.companyAddress]);
  rows.push(
    [],
    [meta.reportTitle.toUpperCase()],
    [],
    ["Date Range", `${fmtDate(meta.dateFrom)} - ${fmtDate(meta.dateTo)}`],
    ["Report Date", fmtDate(meta.reportDate)],
    ["Warehouse", meta.warehouse || "All Warehouses"],
    ["Generated By", meta.generatedBy],
  );
  if (meta.category) rows.push(["Category", meta.category]);
  rows.push([]);
  return rows;
}

export function exportStockWiseExcel(meta: ReportMeta, rows: StockWiseRow[]) {
  const totals = rows.reduce(
    (a, r) => ({
      opening: a.opening + r.openingQty,
      purchase: a.purchase + r.purchaseQty,
      sales: a.sales + r.salesQty,
      adjust: a.adjust + r.adjustQty,
      closing: a.closing + r.closingQty,
      value: a.value + r.stockValue,
      gst: a.gst + r.gst,
      total: a.total + r.totalValue,
    }),
    { opening: 0, purchase: 0, sales: 0, adjust: 0, closing: 0, value: 0, gst: 0, total: 0 },
  );

  const aoa: (string | number)[][] = [
    ...excelMetaRows(meta),
    [
      "S.No.", "Item Code", "Item Name", "UOM",
      "Opening Qty", "Purchase Qty", "Sales Qty", "Adjust Qty", "Closing Qty",
      "Unit Cost (SGD)", "Stock Value (SGD)", "GST 9%", "Total Value (SGD)",
    ],
    ...rows.map((r) => [
      r.sno, r.itemCode, r.itemName, r.uom,
      r.openingQty, r.purchaseQty, r.salesQty, r.adjustQty, r.closingQty,
      Number(r.unitCost.toFixed(2)), Number(r.stockValue.toFixed(2)),
      Number(r.gst.toFixed(2)), Number(r.totalValue.toFixed(2)),
    ]),
    [
      "", "", "GRAND TOTAL", "",
      totals.opening, totals.purchase, totals.sales, totals.adjust, totals.closing,
      "", Number(totals.value.toFixed(2)), Number(totals.gst.toFixed(2)), Number(totals.total.toFixed(2)),
    ],
  ];

  const ws = sheetFromAoa(aoa);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, "Stock Wise");
  XLSX.writeFile(wb, `${safeFile(meta.reportTitle)}-${meta.reportDate}.xlsx`);
}

export function exportBatchWiseExcel(meta: ReportMeta, rows: BatchWiseRow[]) {
  const aoa: (string | number)[][] = [
    ...excelMetaRows(meta),
    [
      "S.No.", "Batch No.", "Item Code", "Item Name", "Warehouse",
      "Mfg. Date", "Expiry Date", "Received Qty", "Sold Qty", "Balance Qty",
      "Unit Cost (SGD)", "Total Value (SGD)",
    ],
    ...rows.map((r) => [
      r.sno, r.batchNo, r.itemCode, r.itemName, r.warehouse,
      fmtDate(r.mfgDate), fmtDate(r.expiryDate),
      r.receivedQty, r.soldQty, r.balanceQty,
      Number(r.unitCost.toFixed(2)), Number(r.totalValue.toFixed(2)),
    ]),
  ];

  const ws = sheetFromAoa(aoa);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, "Batch Wise");
  XLSX.writeFile(wb, `${safeFile(meta.reportTitle)}-${meta.reportDate}.xlsx`);
}

export function exportExpiryWiseExcel(meta: ReportMeta, rows: ExpiryWiseRow[]) {
  const aoa: (string | number)[][] = [
    ...excelMetaRows(meta),
    [
      "S.No.", "Item Code", "Item Name", "Batch No.", "Mfg. Date", "Expiry Date",
      "Days Remaining", "Available Qty", "Warehouse", "Status",
    ],
    ...rows.map((r) => [
      r.sno, r.itemCode, r.itemName, r.batchNo,
      fmtDate(r.mfgDate), fmtDate(r.expiryDate),
      r.daysRemaining, r.availableQty, r.warehouse, r.status,
    ]),
  ];

  const ws = sheetFromAoa(aoa);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, "Expiry Wise");
  XLSX.writeFile(wb, `${safeFile(meta.reportTitle)}-${meta.reportDate}.xlsx`);
}

export function exportGenericExcel(meta: ReportMeta, rows: Record<string, string | number>[]) {
  const keys = Object.keys(rows[0] || {});
  const aoa: (string | number)[][] = [
    ...excelMetaRows(meta),
    keys,
    ...rows.map((r) => keys.map((k) => (r[k] as string | number) ?? "")),
  ];
  const ws = sheetFromAoa(aoa);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, "Report");
  XLSX.writeFile(wb, `${safeFile(meta.reportTitle)}-${meta.reportDate}.xlsx`);
}

export function resolveLayout(reportId: string): InventoryReportLayout {
  if (reportId === "batch_report") return "batch_wise";
  if (reportId === "expiry_report") return "expiry_wise";
  if (reportId === "stock_summary") return "stock_wise";
  return "generic";
}

export { fmtDate, money, qty };
