import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import rolesRouter from "./roles";
import companiesRouter from "./companies";
import purchaseOrdersRouter from "./purchase-orders";
import purchaseQuotationsRouter from "./purchase-quotations";
import quotationsRouter from "./quotations";
import salesOrdersRouter from "./sales-orders";
import invoicesRouter from "./invoices";
import deliveryOrdersRouter from "./delivery-orders";
import settingsRouter from "./settings";
import emailRouter from "./email";
import contactsRouter from "./contacts";
import grnRouter from "./grn";
import stockItemsRouter from "./stock-items";
import vendorsRouter from "./vendors";
import customersRouter from "./customers";
import emailContactsRouter from "./email-contacts";
import stockSerialsRouter from "./stock-serials";
import maintenanceRouter from "./maintenance";
import vendorInvoicesRouter from "./vendor-invoices";
import auditLogsRouter from "./audit-logs";
import agentRouter from "./agent";
import extractPoRouter from "./extract-po";
import accountingRouter from "./accounting";
import whtRouter from "./wht";
import taxFilingsRouter from "./tax-filings";
import aiInvoiceRouter from "./ai/generate-invoice";
import aiFormatRouter from "./ai/format-invoice";
import aiFormatTextRouter from "./ai/format-text";
import aiGenerateEmailRouter from "./ai/generate-email";
import creditNotesRouter from "./credit-notes";
import debitNotesRouter from "./debit-notes";
import proformaInvoicesRouter from "./proforma-invoices";
import projectsRouter from "./projects";
import ackRouter from "./ack";
import expensesRouter from "./expenses";
import incomeRouter from "./income";
import operationsRouter from "./operations";
import inventoryRouter from "./inventory";
import reportsRouter from "./reports";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(rolesRouter);
router.use(companiesRouter);
router.use(extractPoRouter);
router.use(purchaseQuotationsRouter);
router.use(purchaseOrdersRouter);
router.use(quotationsRouter);
router.use(salesOrdersRouter);
router.use(invoicesRouter);
router.use(deliveryOrdersRouter);
router.use("/settings", settingsRouter);
router.use(emailRouter);
router.use(contactsRouter);
router.use(grnRouter);
router.use(stockItemsRouter);
router.use(stockSerialsRouter);
router.use(vendorsRouter);
router.use(customersRouter);
router.use(emailContactsRouter);
router.use(maintenanceRouter);
router.use(vendorInvoicesRouter);
router.use(auditLogsRouter);
router.use(agentRouter);
router.use(accountingRouter);
router.use(whtRouter);
router.use(taxFilingsRouter);
router.use(aiInvoiceRouter);
router.use(aiFormatRouter);
router.use(aiFormatTextRouter);
router.use(aiGenerateEmailRouter);
router.use(creditNotesRouter);
router.use(debitNotesRouter);
router.use(proformaInvoicesRouter);
router.use(projectsRouter);
router.use(ackRouter);
router.use(expensesRouter);
router.use(incomeRouter);
router.use(operationsRouter);
router.use(inventoryRouter);
router.use(reportsRouter);

export default router;
