import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import companiesRouter from "./companies";
import purchaseOrdersRouter from "./purchase-orders";
import quotationsRouter from "./quotations";
import invoicesRouter from "./invoices";
import deliveryOrdersRouter from "./delivery-orders";
import settingsRouter from "./settings";
import emailRouter from "./email";
import contactsRouter from "./contacts";
import grnRouter from "./grn";
import stockItemsRouter from "./stock-items";
import vendorsRouter from "./vendors";
import customersRouter from "./customers";
import emailContactsRouter from "./email-contacts";
import stockSerialsRouter from "./stock-serials";
import maintenanceRouter from "./maintenance";
import vendorInvoicesRouter from "./vendor-invoices";
import auditLogsRouter from "./audit-logs";
import agentRouter from "./agent";
import extractPoRouter from "./extract-po";
import accountingRouter from "./accounting";
import whtRouter from "./wht";
import taxFilingsRouter from "./tax-filings";
import aiInvoiceRouter from "./ai/generate-invoice";
import aiFormatRouter from "./ai/format-invoice";
import aiFormatTextRouter from "./ai/format-text";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(companiesRouter);
router.use(extractPoRouter);
router.use(purchaseOrdersRouter);
router.use(quotationsRouter);
router.use(invoicesRouter);
router.use(deliveryOrdersRouter);
router.use("/settings", settingsRouter);
router.use(emailRouter);
router.use(contactsRouter);
router.use(grnRouter);
router.use(stockItemsRouter);
router.use(stockSerialsRouter);
router.use(vendorsRouter);
router.use(customersRouter);
router.use(emailContactsRouter);
router.use(maintenanceRouter);
router.use(vendorInvoicesRouter);
router.use(auditLogsRouter);
router.use(agentRouter);
router.use(accountingRouter);
router.use(whtRouter);
router.use(taxFilingsRouter);
router.use(aiInvoiceRouter);
router.use(aiFormatRouter);
router.use(aiFormatTextRouter);

export default router;
