// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/option-a/FormView.tsx": () => import("../components/mockups/option-a/FormView.tsx"),
  "./components/mockups/option-a/PdfView.tsx": () => import("../components/mockups/option-a/PdfView.tsx"),
  "./components/mockups/logout-opts/OptionA.tsx": () => import("../components/mockups/logout-opts/OptionA.tsx"),
  "./components/mockups/logout-opts/OptionB.tsx": () => import("../components/mockups/logout-opts/OptionB.tsx"),
  "./components/mockups/logout-opts/OptionC.tsx": () => import("../components/mockups/logout-opts/OptionC.tsx")
};
