import { pool } from "@workspace/db";
import { logger } from "./lib/logger";

const OPERATIONS_TABLE_MIGRATIONS = [
  `CREATE TABLE IF NOT EXISTS assets (
    id SERIAL PRIMARY KEY,
    company_id INTEGER NOT NULL,
    tag TEXT NOT NULL,
    type TEXT NOT NULL,
    category TEXT NOT NULL,
    serial TEXT NOT NULL,
    model TEXT,
    manufacturer TEXT,
    status TEXT NOT NULL DEFAULT 'available',
    condition TEXT,
    assigned_to TEXT,
    location TEXT,
    vendor TEXT,
    vendor_id INTEGER,
    invoice_number TEXT,
    purchase_date TIMESTAMPTZ,
    warranty_expiry TIMESTAMPTZ,
    cost TEXT,
    depreciation_start_date TIMESTAMPTZ,
    useful_life_years INTEGER,
    depreciation_method TEXT,
    description TEXT,
    has_license BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
  )`,
  `CREATE TABLE IF NOT EXISTS employees (
    id SERIAL PRIMARY KEY,
    company_id INTEGER NOT NULL,
    employee_id TEXT NOT NULL,
    user_id INTEGER,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NOT NULL,
    address TEXT NOT NULL,
    department TEXT NOT NULL,
    designation TEXT NOT NULL,
    join_date TIMESTAMPTZ NOT NULL,
    status TEXT NOT NULL DEFAULT 'active',
    salary TEXT,
    annual_salary TEXT,
    nationality TEXT,
    pr_status TEXT,
    date_of_birth TIMESTAMPTZ,
    passport_number TEXT,
    passport_expiry TIMESTAMPTZ,
    visa_number TEXT,
    visa_expiry TIMESTAMPTZ,
    visa_type TEXT,
    visa_remarks TEXT,
    nric_number TEXT,
    nric_expiry TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
  )`,
  `CREATE TABLE IF NOT EXISTS dependents (
    id SERIAL PRIMARY KEY,
    company_id INTEGER NOT NULL,
    employee_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    relationship TEXT NOT NULL,
    passport_number TEXT,
    passport_expiry TIMESTAMPTZ,
    visa_number TEXT,
    visa_expiry TIMESTAMPTZ,
    visa_type TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
  )`,
  `CREATE TABLE IF NOT EXISTS licenses (
    id SERIAL PRIMARY KEY,
    company_id INTEGER NOT NULL,
    asset_id INTEGER,
    name TEXT NOT NULL,
    license_key TEXT NOT NULL,
    type TEXT NOT NULL,
    seats INTEGER DEFAULT 1,
    vendor_id INTEGER,
    purchase_date TIMESTAMPTZ,
    expiry_date TIMESTAMPTZ,
    cost TEXT,
    renewal_cycle TEXT DEFAULT 'none',
    status TEXT DEFAULT 'active',
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
  )`,
  `CREATE TABLE IF NOT EXISTS asset_assignments (
    id SERIAL PRIMARY KEY,
    company_id INTEGER NOT NULL,
    asset_id INTEGER NOT NULL,
    employee_id INTEGER NOT NULL,
    date_assigned TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    date_returned TIMESTAMPTZ,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
  )`,
  `CREATE TABLE IF NOT EXISTS maintenance_records (
    id SERIAL PRIMARY KEY,
    company_id INTEGER NOT NULL,
    asset_id INTEGER NOT NULL,
    issue_description TEXT NOT NULL,
    resolution TEXT,
    service_date TIMESTAMPTZ NOT NULL,
    next_maintenance_date TIMESTAMPTZ,
    cost TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
  )`,
  `CREATE TABLE IF NOT EXISTS employee_payroll (
    id SERIAL PRIMARY KEY,
    company_id INTEGER NOT NULL,
    employee_id INTEGER NOT NULL,
    base_salary NUMERIC(10,2) NOT NULL,
    payroll_period TEXT NOT NULL DEFAULT 'monthly',
    cpf_employee_rate NUMERIC(5,2),
    cpf_employer_rate NUMERIC(5,2),
    allowances JSONB DEFAULT '[]',
    deductions JSONB DEFAULT '[]',
    bank_name TEXT,
    bank_account TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
  )`,
  `CREATE TABLE IF NOT EXISTS payroll_records (
    id SERIAL PRIMARY KEY,
    company_id INTEGER NOT NULL,
    employee_id INTEGER NOT NULL,
    payroll_config_id INTEGER,
    pay_period_start TIMESTAMPTZ NOT NULL,
    pay_period_end TIMESTAMPTZ NOT NULL,
    gross_pay NUMERIC(12,2) NOT NULL,
    net_pay NUMERIC(12,2) NOT NULL,
    cpf_employee NUMERIC(12,2) DEFAULT 0,
    cpf_employer NUMERIC(12,2) DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'draft',
    processed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
  )`,
  `CREATE TABLE IF NOT EXISTS service_reports (
    id SERIAL PRIMARY KEY,
    company_id INTEGER NOT NULL,
    csr_number TEXT NOT NULL,
    customer_id INTEGER,
    customer_name TEXT NOT NULL,
    customer_address TEXT,
    customer_contact_person TEXT,
    customer_phone TEXT,
    customer_email TEXT,
    support_requested_by TEXT NOT NULL,
    support_request_date TIMESTAMPTZ NOT NULL,
    problem_description TEXT NOT NULL,
    engineer_id INTEGER,
    service_date TIMESTAMPTZ NOT NULL,
    service_time TEXT NOT NULL,
    hours_charged NUMERIC(4,2) NOT NULL,
    service_details TEXT NOT NULL,
    remarks TEXT,
    priority_level TEXT NOT NULL DEFAULT 'medium',
    status TEXT NOT NULL DEFAULT 'draft',
    created_by INTEGER,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
  )`,
  `CREATE TABLE IF NOT EXISTS employee_documents (
    id SERIAL PRIMARY KEY,
    company_id INTEGER NOT NULL,
    employee_id INTEGER NOT NULL,
    document_type TEXT NOT NULL,
    file_path TEXT NOT NULL,
    issue_date TIMESTAMPTZ,
    expiry_date TIMESTAMPTZ,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
  )`,
];

export async function migrateOperationsTables(): Promise<void> {
  for (const statement of OPERATIONS_TABLE_MIGRATIONS) {
    await pool.query(statement);
  }
  logger.info("Operations tables migration complete");
}
