/** Canonical module keys used for sidebar access and user_companies.modules. */
export const APP_ALL_MODULES = [
  "dashboard",
  "assets",
  "licenses",
  "employees",
  "payroll",
  "service_reports",
  "purchase_orders",
  "quotations",
  "invoices",
  "proforma_invoices",
  "credit_notes",
  "delivery_orders",
  "grn",
  "stock_items",
  "warehouses",
  "stock_transfer",
  "inventory_reports",
  "vendors",
  "customers",
  "projects",
  "accounting_coa",
  "accounting_je",
  "accounting_gl",
  "accounting_tb",
  "accounting_bs",
  "accounting_pl",
  "accounting_cf",
  "accounting_gst_f5",
  "accounting_gst_f7",
  "accounting_gst_io",
  "accounting_wht",
  "accounting_eci",
  "accounting_formcs",
  "accounting_iaf",
  "accounting_ar",
  "accounting_ar_aging",
  "accounting_cust_stmt",
  "accounting_ap",
  "accounting_ap_aging",
  "accounting_vendor_stmt",
  "user_management",
  "audit_log",
  "settings",
] as const;

export type AppModuleKey = (typeof APP_ALL_MODULES)[number];
