export const COUNTRIES = [
  "Singapore",
  "India",
  "Malaysia",
  "Indonesia",
  "Thailand",
  "Philippines",
  "Vietnam",
  "China",
  "Japan",
  "South Korea",
  "Hong Kong",
  "Taiwan",
  "Australia",
  "New Zealand",
  "United States",
  "United Kingdom",
  "Germany",
  "France",
  "Netherlands",
  "Sweden",
  "Switzerland",
  "Canada",
  "Brazil",
  "South Africa",
  "United Arab Emirates",
  "Saudi Arabia",
  "Bangladesh",
  "Sri Lanka",
  "Pakistan",
  "Other",
];
